services:

  shard-02-primary:
    build: 
      context: mongodb-build
    image: kay-mongo:4
    container_name: shard-02-primary
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard_02_primary_db:/data/db
      - mongodb_cluster_shard_02_primary_config:/data/configdb
    ports:
      - 27125:27017
    restart: always
    networks:
      - shard-02
  shard-02-secondary-01:
    build: 
      context: mongodb-build
    image: kay-mongo:4
    container_name: shard-02-secondary-01
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard_02_secondary_01_db:/data/db
      - mongodb_cluster_shard_02_secondary_01_config:/data/configdb
    ports:
      - 27126:27017
    restart: always
    networks:
      - shard-02
  shard-02-secondary-02:
    build: 
      context: mongodb-build
    image: kay-mongo:4
    container_name: shard-02-secondary-02
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard_02_secondary_02_db:/data/db
      - mongodb_cluster_shard_02_secondary_02_config:/data/configdb
    ports:
      - 27127:27017
    restart: always
    networks:
      - shard-02

networks:
  shard-02:

volumes:
  mongodb_cluster_shard_02_primary_db:
  mongodb_cluster_shard_02_primary_config:
  
  mongodb_cluster_shard_02_secondary_01_db:
  mongodb_cluster_shard_02_secondary_01_config:
  
  mongodb_cluster_shard_02_secondary_02_db:
  mongodb_cluster_shard_02_secondary_02_config:
